### ISSUE TITLE
trouble using C API in C#

### ISSUE THREAD

**Issue by zzzz465** [MinusKelvin/cold-clear#5]
hello, I'm writing a C# API with C API, to use it in .NET
however, with evaluating with a returned pointer from cc_launch_async,
the cc bot immediately dies.
also, I found that the field "max_nodes" in struct CCOptions' type is int32, but the actual value in options.yaml(preview version) is "18446744073709551615", which is uint64.

**Comment by MinusKelvin** [comment]
I need an example of code which causes this.

On the `max_nodes` field, it has been changed to `uint32_t` in the latest master, and the default value is now 4 billion.

**Comment by zzzz465** [comment]
C# API Code
https://gist.github.com/zzzz465/8590b691dd3ebb57050e9d04259ebbd4

Test Code
https://gist.github.com/zzzz465/4a4981827b36bd9d73dd6fd87c667e27

ps. 
I never used rust and used C++ very little before so there could be a wrong code or something.

**Comment by zzzz465** [comment]
I didn't write proper codes to pass marshaled data to C API, I'll upload the result after fixing this.

**Comment by MinusKelvin** [comment]
Are you building from source, or using the dll from build 1?

**Comment by zzzz465** [comment]
1) I compiled latest git source(2020/03/13) with rust compiler, and used cold-clear/target/release/cold_clear.dll
2) I tried changing passing struct with ref, to marshaled intPtr but still the bot dies.

**Comment by MinusKelvin** [comment]
It looks like you're passing a pointer to the pointer to the `CCAsyncBot`, you need to pass the pointer to the `CCAsyncBot`.

**Comment by zzzz465** [comment]
I removed `ref` keyword in extern method so the pointer(not pointer's pointer) is passed to the method.
now the program ends successfully without any `AccessViolation` but the bot still dies immediately.

Test code:
https://gist.github.com/zzzz465/fd7aad117c17c3c63bab5edbbadd5ada

edited API code:
https://gist.github.com/zzzz465/8590b691dd3ebb57050e9d04259ebbd4

**Comment by MinusKelvin** [comment]
I can't tell what the problem is; you seem to be using it correctly. The C API works fine for me. Can you try running this C code and tell me if it outputs 0 or 1?
```C
#include "coldclear.h"
#include <stdio.h>
void main() {
    CCOptions options;
    CCWeights weights;
    cc_default_options(&options);
    cc_default_weights(&weights);
    CCAsyncBot *bot = cc_launch_async(&options, &weights);
    printf("%d\n", cc_is_dead_async(bot));
    cc_destroy_async(bot);
}
```

**Comment by MinusKelvin** [comment]
I checked the C# type marshalling docs, it says that C# `bool` is marshalled as a 4-byte integer, but the C API uses the C99 `bool` type which is a 1-byte integer. This is likely to be the problem.

**Comment by zzzz465** [comment]
I found the wiredness of C# marshaling.
```
        [StructLayout(LayoutKind.Sequential)]
        public struct structData
        {
            [MarshalAs(UnmanagedType.I1)]
            public bool use_hold;
        }

        static void MarshalTest()
        {
            structData data = new structData();
            var size = Marshal.SizeOf(data); // size = 1 (byte) (expected)
        }
```
if I use that struct, the marshaled size is 1 byte.
however if I use this code,
```
        [StructLayout(LayoutKind.Sequential)]
        public struct structData
        {
            public CCMovementMode mode;
            [MarshalAs(UnmanagedType.I1)]
            public bool use_hold;
        }

        static void MarshalTest()
        {
            structData data = new structData();
            var size = Marshal.SizeOf(data); // size 5 (byte) expected, but the actual size is 8 (byte)
        }
```
`[MarshalAs(UnmanagedType.I1)]` attribute is ignored and the size become 8 byte, not 5, I'm searching proper way to fix this.

seems struct is sliced by 4 bytes, `Marshal.Sizeof(CCOptions)` is 20 byte, it means that `use_hold` and `speculate` takes 2 bytes each. it should be 18 bytes according to the C API code.

**Comment by SoRA-X7** [comment]
I'm also trying to do the same thing
Maybe you need [StructLayout(LayoutKind.Sequential, Pack = 1)] to your struct

**Comment by zzzz465** [comment]
yeah I just found that option, trying rn.

**Comment by zzzz465** [comment]
`CCOptions` = 18 byte, and `CCWeights` = 173 byte
I got an error.
```
thread '<unnamed>' panicked at 'Invalid number of threads: 0', <::std::macros::panic macros>:2:4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
which is weird cuz I gave thread number 1
`            var options = new CCOptions() { mode = CCMovementMode.CC_0G, use_hold = true, speculate = true, min_nodes = 0, max_nodes = 999999, threads = 1 };`

if I pass struct by allocating memories to them, marshal structs and passing it by IntPtr, it even doesn't provide any error messages, of course the bot still dies immediately.

**Comment by SoRA-X7** [comment]
Try setting internal types of all the enums to `byte`

**Comment by MinusKelvin** [comment]
Remember that C inserts padding to satisfy alignment requirements. It seems that C# does the same thing. For example, the `CCOptions` struct is defined like this:
```C
typedef struct CCOptions {
    CCMovementMode mode;
    bool use_hold;
    bool speculate;
    uint32_t min_nodes;
    uint32_t max_nodes;
    uint32_t threads;
} CCOptions;
```
but to satisfy the 4-byte alignment requirement of of the `uint32_t` for the `min_nodes` field, it inserts padding making the struct look like this:
```C
typedef struct CCOptions {
    CCMovementMode mode;
    bool use_hold;
    bool speculate;
    char _padding[2];
    uint32_t min_nodes;
    uint32_t max_nodes;
    uint32_t threads;
} CCOptions;
```
So `sizeof(CCOptions)` is 20 bytes. It will also insert padding at the end of the struct so that if you have an array of the struct, the structure's alignment will be satisfied. Your example with a 4-byte field then a 1-byte field demonstrates this; to satisfy the alignment requirement of the structure (4 bytes), 3 bytes of padding are added to the end of the struct, making its size 8 bytes.

**Comment by SoRA-X7** [comment]
My api interface which seems to work(but not completely tested):
https://gist.github.com/SoRA-X7/6a902891e265bb6be911f1c199c6b6e7

**Comment by zzzz465** [comment]
It works but I don't know why it works, C API accepts CCOptions pointer but @SoRA-X7 's code pass managed struct object, not even a pointer.

**Comment by zzzz465** [comment]
I found it, the main reason why the return value always true because it wasn't marshaled properly. I should done that before.

**Comment by zzzz465** [comment]
it works fine I think, I added some pieces and got a result.
this is the first time using interop for me, thanks for the help.

**Comment by zzzz465** [comment]
![Honeycam 2020-03-17 17-56-56](https://user-images.githubusercontent.com/46273764/76839367-b9c0b580-6878-11ea-8aec-2abf0cf97cd2.gif)

(quick visulization of C# API with OpenCV)
@MinusKelvin @SoRA-X7 works well, thanks.
